counting_topics = ['counting-with-small-numbers',
                   'counting-in-order',
                   'number-grid',
                   'numbers-to-120',
                   'counting-in-scenes',
                   'how-many-objects-1',
                   'counting-objects-2',
                   'comparing-groups-through-10-example',
                   'comparing-numbers-through-10-example',
                   'count-by-category',
                   'skip-counting-by-5-example',
                   'skip-counting-by-100-example',
                   'counting-by-tens-examples']


place_value_topics = ['teens-and-ten',
                      'monkeys-for-party',
                      'place-value-introduction',
                      'place-value-example',
                      'place-value-1',
                      'place-value-2',
                      'rep-quantity-with-digits',
                      'greater-than-and-less-than-symbols',
                      'place-value-blocks',
                      'comparing-whole-numbers',
                      'comparing-whole-number-place-values']


addition_topics = ['addition-introduction',
                   'basic-addition',
                   'making-5',
                   'getting-to-10-by-filling-boxes',
                   'adding-to-10-example',
                   'adding-fruit',
                   'addition-word-problems-within-10',
                   'addition-using-groups-of-10-intro',
                   'addition-using-groups-of-10-and-100',
                   'adding-whole-numbers-by-their-place-values',
                   'understanding-place-value-when-adding-tens',
                   'understanding-place-value-when-adding-ones',
                   'commutative-law-of-addition']


subtraction_topics = ['subtraction-introduction',
                      'basic-subtraction',
                      'subtraction-2',
                      'understanding-place-value-while-subtracting-ones',
                      'subtraction-word-problems-within-10',
                      'understanding-place-value-when-subtracting-tens',
                      'subtracting-within-20',
                      'comparing-subtracting-1-and-10']


addition_subtraction_topics = ['relating-addition-and-subtraction',
                               'addition-and-subtraction-within-10',
                               'equal-sign',
                               'sea-monsters-and-superheroes',
                               'exercising-gorillas',
                               'comparison-word-problems',
                               'more-comparison-word-problems',
                               'repeated-addition-example',
                               'adding-two-digit-numbers-no-regrouping',
                               'subtracting-two-digit-numbers-without-regrouping',
                               'correct-number-lines-for-addition-and-subtraction',
                               'adding-and-subtracting-on-number-line-word-problems',
                               'missing-numbers-in-addition-and-subtraction-within-100']


measurement_data_topics = ['order-by-length',
                           'measuring-lengths-2',
                           'measuring-lengths-with-different-units',
                           'comparing-lengths',
                           'estimating-lengths',
                           'length-word-problems',
                           'basic-measurement',
                           'picture-graphs',
                           'making-line-plots',
                           'reading-bar-graph-examples',
                           'solving-problems-with-bar-graphs-2',
                           'creating-picture-and-bar-graphs-2-exercise-examples',
                           'introduction-to-line-plots',
                           'making-line-plots',
                           'telling-time-exercise-example-1',
                           'telling-time-exercise-example-2',
                           'counting-dollars',
                           'counting-american-coins']


geometry_topics = ['sides-corners',
                   'recognizing-shapes',
                   'compose-shapes',
                   'halves-and-fourths',
                   'equal-parts-of-circles-and-rectangles',
                   'lines-line-segments-and-rays',
                   'identifying-rays',
                   'measuring-segments',
                   'congruent-segments',
                   'parallel-and-perpendicular-lines-intro',
                   'identifying-parallel-and-perpendicular-lines',
                   'drawing-lines-exercise-example',
                   'geometric-precision-practice',
                   'the-golden-ratio',
                   'geometry-shapes',
                   'geometry-properties-shapes',
                   'classifying-shapes',
                   'classifying-shapes-examples']
